Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-10, with the labels that each got.

#246 [KOGITO-3463] - Update clone-repo script for CI specific actions
  Jenkinsfile
  Jenkinsfile.deploy
  Jenkinsfile.promote
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#250 [KOGITO-3463] Corrected clone-repo.sh
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#244 [KOGITO-3469] - Investigate maven multi module tests on Kogito s2i image
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: needs review :mag:

#245 [KOGITO-2003] - Behave tests with native builds and persistene enable…
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: needs review :mag:

#253 [KOGITO-3553] - Ignore Self signed certificates from maven while bui…
  Jenkinsfile
  Jenkinsfile.deploy
  modules/kogito-maven/3.6.x/added/configure-maven.sh
  modules/kogito-maven/3.6.x/module.yaml
  modules/kogito-maven/tests/bats/maven-settings.bats
  scripts/common.py
  scripts/update-tests.py
Labels: hacktoberfest, hacktoberfest-accepted, needs review :mag:

#251 [KOGITO-3510] Deploy/Promote pipelines: set credentials as params
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:

#249 [KOGITO-3467] Script to retrieve list of images
  Jenkinsfile
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  kogito-quarkus-jvm-ubi8-overrides.yaml
  kogito-quarkus-ubi8-overrides.yaml
  kogito-quarkus-ubi8-s2i-overrides.yaml
  kogito-springboot-ubi8-overrides.yaml
  kogito-springboot-ubi8-s2i-overrides.yaml
  scripts/common.py
  scripts/list-images.py
  scripts/push-local-registry.sh
  scripts/push-staging.py
Labels: needs review :mag:

#256 [KOGITO-3580] Checkout repo in promote pipeline
  Jenkinsfile.promote
Labels: needs review :mag:

#257 [KOGITO-3581] Clean workspaces at stage end
  Jenkinsfile.deploy
Labels: needs review :mag:

#258 [KOGITO-3482] - Remove handling of runtime configuration from kogtio …
  kogito-jobs-service-overrides.yaml
  modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
Labels: ready :rocket:

#262 [KOGITO-3639] - Ignore Verify if the s2i build is finished as expected performing a native build with persistence enabled Scenario on kogito images
  modules/kogito-data-index/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: needs review :mag:

#264 [0.17.x][KOGITO-3639] Ignore Verify if the s2i build is finished a…
  modules/kogito-data-index/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: cherry-pick :cherries:, needs review :mag:

#263 [0.17.x] [KOGITO-3643] Setup 0.17.0-SNAPSHOT version
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#265 [KOGITO-3094] - Provide data-index-infinispan/mongodb as independent …
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  kogito-data-index-infinispan-overrides.yaml
  kogito-data-index-mongodb-overrides.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index-common/added/launch/kogito-data-index.sh
  modules/kogito-data-index-common/configure
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-common/tests/bats/kogito-data-index.bats
  modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
  modules/kogito-data-index-infinispan/configure
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/added/kogito-app-launch.sh
  modules/kogito-data-index-mongodb/configure
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-data-index/added/launch/kogito-data-index.sh
  modules/kogito-data-index/module.yaml
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  modules/kogito-explainability/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/list-images.py
  scripts/manage-kogito-version.py
  scripts/push-local-registry.sh
  scripts/push-staging.py
  scripts/run-bats.sh
  scripts/update-maven-artifacts.py
  tests/features/common-build-runtime.feature
  tests/features/common.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/data-index/kogito-data-index-infinispan.feature
  tests/features/data-index/kogito-data-index-mongodb.feature
  tests/features/kogito-data-index.feature
Labels: needs review :mag:

#267 [KOGITO-3722] Correcting tests
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: ready :rocket:

#272 [KOGITO-3746] - Fix failing test on kogito images master
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: needs review :mag:
