Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-04, with the labels that each got.

#124 [master][KOGITO-1673] - Images should deploy version without micro version in tag
  Makefile
Labels: ready :rocket:

#127 [0.9.x][KOGITO-1673] - Images should deploy version without micro version in tag
  Makefile
Labels: cherry-pick :cherries:

#128 [master][KOGITO-1636] - Native binary is not recognized in binary bui…
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-s2i-core/added/s2i-core
Labels: needs review :mag:, ready :rocket:

#129 [0.9.x][KOGITO-1636] - Native binary is not recognized in binary bui…
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-s2i-core/added/s2i-core
Labels: cherry-pick :cherries:, ready :rocket:

#120 [master][KOGITO-1636] - Add missing test coverage for runtime_assemble
  modules/kogito-s2i-core/tests/bats/mocks/myapp-0.0.1-runner
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
Labels: needs review :mag:

#131 [0.9.x][KOGITO-1636] - Add missing test coverage for runtime_assemble
  modules/kogito-s2i-core/tests/bats/mocks/myapp-0.0.1-runner
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
Labels: cherry-pick :cherries:, needs review :mag:

#130 [master][KOGITO-1774] - Update Jobs-services, data-index and mgmt con…
  modules/kogito-data-index/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
Labels: ready :rocket:

#136 [0.9.x][KOGITO-1770] - Updating images tests to reflect new examples naming
  kogito-quarkus-jvm-overrides.yaml
  kogito-quarkus-overrides.yaml
  tests/features/kogito-quarkus-jvm-ubi8.feature
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8.feature
  tests/test-apps/clone-repo.sh
Labels: cherry-pick :cherries:, needs review :mag:

#135 [0.9.x][KOGITO-1774] - Update Jobs-services, data-index and mgmt cons…
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  tests/features/kogito-quarkus-jvm-ubi8.feature
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#137 [0.9.x][KOGITO-1828] Update Jobs-services, data-index and mgmt console SNAPSHOT artefacts
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
Labels: ready :rocket:

#134 [master][KOGITO-1490] - Improve Kogito images README file
  LICENSE
  README.md
  docsimg/kogito.png
  kogito-data-index-overrides.yaml
  kogito-jobs-service-overrides.yaml
  kogito-management-console-overrides.yaml
  kogito-quarkus-jvm-overrides.yaml
  kogito-quarkus-overrides.yaml
  kogito-quarkus-s2i-overrides.yaml
  kogito-springboot-overrides.yaml
  kogito-springboot-s2i-overrides.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-quarkus-jvm/README.md
  modules/kogito-quarkus-s2i/README.md
  modules/kogito-quarkus-s2i/s2i/bin/usage
  modules/kogito-quarkus/README.md
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/kogito-springboot-s2i/README.md
  modules/kogito-springboot-s2i/s2i/bin/usage
  modules/kogito-springboot/README.md
  modules/kogito-springboot/s2i/bin/usage
Labels: needs review :mag:, ready :rocket:

#142 [0.9.x][KOGITO-1909] - Behave tests on Kogito images fails when non n…
  kogito-quarkus-s2i-overrides.yaml
Labels: cherry-pick :cherries:, needs review :mag:, ready :rocket:

#143 [master][KOGITO-1909] - Behave tests on Kogito images fails when non …
  kogito-quarkus-s2i-overrides.yaml
Labels: needs review :mag:, ready :rocket:

#141 [KOGITO-1727] - Release Kogito Images 0.9.1
  Makefile
  image.yaml
  kogito-imagestream.yaml
  kogito-quarkus-s2i-overrides.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/clean.sh
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  tests/features/kogito-quarkus-jvm-ubi8.feature
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-quarkus-ubi8.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#147 [KOGITO-1672] - Improve Kogito Images Behave tests
  Jenkinsfile
  Makefile
  README.md
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  modules/kogito-infinispan-properties/added/kogito-infinispan-properties.sh
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-infinispan-properties/tests/bats/kogito-infinispan-properties.bats
  scripts/README.md
  scripts/manage-kogito-version.py
  tests/features/common.feature
  tests/features/kogito-data-index.feature
  tests/features/kogito-jobs-service.feature
  tests/features/kogito-management-console.feature
  tests/features/kogito-quarkus-jvm-ubi8.feature
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-quarkus-ubi8.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#145 [0.9.x][KOGITO-1948] Updated to 0.9.2-rc1
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
Labels: needs review :mag:, on hold :hand:

#150 [0.10.x][KOGITO-1672] - Improve Kogito Images Behave tests
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: cherry-pick :cherries:, ready :rocket:

#148 [0.10.x][KOGITO-1227] - Create pipeline to build and test Kogito images when a new Pull Request is created.
  Jenkinsfile
Labels: cherry-pick :cherries:
