Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-11, with the labels that each got.

#271 [KOGITO-3745] RepoURL should be ignored by mirror
  Jenkinsfile.deploy
  modules/kogito-maven/3.6.x/added/configure-maven.sh
Labels: needs review :mag:

#270 [KOGITO-3376] Remove post-hook persistence script
  modules/kogito-persistence/added/kogito-persistence.sh
  modules/kogito-persistence/added/post-hook-persistence.sh
  modules/kogito-persistence/configure
  modules/kogito-persistence/tests/bats/expected/patch_cm_travel_agency.json
  modules/kogito-persistence/tests/bats/expected/patch_empty_data.json
  modules/kogito-persistence/tests/bats/kogito-persistence.bats
  modules/kogito-persistence/tests/bats/mocks/config_map.json
  modules/kogito-persistence/tests/bats/mocks/config_map_empty_annotations.json
  modules/kogito-persistence/tests/bats/mocks/config_map_file1_only.json
  modules/kogito-persistence/tests/bats/mocks/config_map_no_annotations.json
  modules/kogito-persistence/tests/bats/mocks/travels.proto
  modules/kogito-persistence/tests/bats/mocks/visaApplications.proto
  modules/kogito-persistence/tests/bats/post-hook-persistence.bats
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: needs review :mag:

#275 [KOGITO-3094] - Provide data-index-infinispan/mongodb as independent …
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  kogito-data-index-infinispan-overrides.yaml
  kogito-data-index-mongodb-overrides.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index-common/added/launch/kogito-data-index.sh
  modules/kogito-data-index-common/configure
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-common/tests/bats/kogito-data-index.bats
  modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
  modules/kogito-data-index-infinispan/configure
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/added/kogito-app-launch.sh
  modules/kogito-data-index-mongodb/configure
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-data-index/added/launch/kogito-data-index.sh
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  scripts/README.md
  scripts/common.py
  scripts/list-images.py
  scripts/manage-kogito-version.py
  scripts/push-local-registry.sh
  scripts/push-staging.py
  scripts/run-bats.sh
  scripts/update-maven-artifacts.py
  tests/features/common-build-runtime.feature
  tests/features/common.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/data-index/kogito-data-index-infinispan.feature
  tests/features/data-index/kogito-data-index-mongodb.feature
  tests/features/kogito-data-index.feature
Labels: cherry-pick :cherries:, needs review :mag:

#277 [KOGITO-3006] Allow to set artifacts version
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:, needs-cherry-pick :cherries:

#276 [cherry-pick][KOGITO-3006] Allow to set artifacts version in pipeline
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: cherry-pick :cherries:, needs review :mag:

#280 [KOGITO-3837] Update master to 2.0.0-snapshot
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: needs review :mag:

#282 [KOGITO-3861] - kogito user does not have permission on home director…
  modules/kogito-data-index-mongodb/added/kogito-app-launch.sh
  modules/kogito-system-user/add-user
  tests/features/common.feature
Labels: ready :rocket:
