Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-09, with the labels that each got.

#231 KOGITO-3224 - Enable explainability messaging in trusty image
  kogito-explainability-overrides.yaml
  modules/kogito-explainability/added/kogito-app-launch.sh
  modules/kogito-explainability/added/launch/kogito-explainability.sh
  modules/kogito-explainability/tests/bats/kogito-explainability.bats
  modules/kogito-trusty/added/launch/kogito-trusty.sh
  modules/kogito-trusty/tests/bats/kogito-trusty.bats
  tests/features/kogito-explainability.feature
  tests/features/kogito-trusty.feature
Labels: ready :rocket:

#230 [KOGITO-2890] - Provide alternative persistence solutions for data index
  README.md
  kogito-data-index-overrides.yaml
  modules/kogito-data-index/added/kogito-app-launch.sh
  modules/kogito-data-index/added/launch/kogito-data-index.sh
  modules/kogito-data-index/configure
  modules/kogito-data-index/module.yaml
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  modules/kogito-explainability/module.yaml
  modules/kogito-jobs-service/added/kogito-app-launch.sh
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
  modules/kogito-management-console/module.yaml
  modules/kogito-quarkus-jvm/tests/bats/kogito-quarkus-jvm.bats
  modules/kogito-quarkus-s2i/tests/bats/kogito-quarkus-s2i.bats
  modules/kogito-quarkus/tests/bats/kogito-quarkus-native.bats
  modules/kogito-springboot-s2i/tests/bats/kogito-springboot-s2i.bats
  modules/kogito-springboot/tests/bats/kogito-springboot.bats
  modules/kogito-trusty/added/kogito-app-launch.sh
  modules/kogito-trusty/module.yaml
  scripts/README.md
  scripts/update-maven-artifacts.py
  tests/features/kogito-data-index.feature
Labels: ready :rocket:

#227 KOGITO-3180 - add trusty-ui image
  Jenkinsfile
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  README.md
  kogito-trusty-ui-overrides.yaml
  modules/kogito-trusty-ui/added/kogito-app-launch.sh
  modules/kogito-trusty-ui/added/launch/kogito-trusty-ui.sh
  modules/kogito-trusty-ui/configure
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty-ui/tests/bats/kogito-trusty-ui.bats
  scripts/README.md
  scripts/common.py
  scripts/push-local-registry.sh
  scripts/push-staging.py
  scripts/run-bats.sh
  scripts/update-maven-artifacts.py
  tests/features/kogito-trusty-ui.feature
Labels: needs review :mag:, on hold :hand:, ready :rocket:

#233 KOGITO-3303 - update imagestream with trusty-ui and explainability
  kogito-imagestream.yaml
Labels: ready :rocket:

#234 Fix common.py script
  scripts/common.py
Labels: ready :rocket:

#235 [0.15.x] Fix trusty ui script backport
  kogito-imagestream.yaml
  scripts/common.py
Labels: ready :rocket:

#236 Quick fix for setting correct version in update-maven-artifacts.py
  scripts/update-maven-artifacts.py
Labels: needs review :mag:

#238 Change promote to ask a confirmation if no change in setting artifacts
  Jenkinsfile.promote
Labels: needs review :mag:

#240 Change promote to ask a confirmation if no change in setting artifacts
  Jenkinsfile.promote
Labels: cherry-pick :cherries:, needs review :mag:

#241 [KOGITO-3446] - Remove KAFKA_BOOTSTRAP_SERVERS env check from Jobs se…
  kogito-jobs-service-overrides.yaml
  modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
  tests/features/kogito-jobs-service.feature
Labels: needs review :mag:

#242 [KOGITO-3461] Moved KOGITO_VERSION to image.yaml
  image.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  scripts/common.py
  scripts/manage-kogito-version.py
  scripts/update-maven-artifacts.py
Labels: needs review :mag:

#243 [KOGITO-3433] - Update Graalvm version to 20.2.0
  README.md
  kogito-quarkus-overrides.yaml
  kogito-quarkus-s2i-overrides.yaml
  modules/kogito-graalvm-installer/20.x-java-1.8/module.yaml
  modules/kogito-graalvm-installer/20.x-java-11/module.yaml
  modules/kogito-graalvm-scripts/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
Labels: needs review :mag:
