Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-08, with the labels that each got.

#196 [KOGITO-2353] - Add option to run the kogito images' bats tests using…
  .github/workflows/kogito-images-pr-check.yml
  .github/workflows/run-bats-tests.yml
  .github/workflows/validate-imagestreams.yml
  .gitignore
  Makefile
  scripts/run-bats.sh
Labels: needs review :mag:

#199 [KOGITO-2912] Reorganized scripts
  Jenkinsfile-Nightly
  Jenkinsfile.deploy
  scripts/README.md
  scripts/common.py
  scripts/manage-kogito-version.py
  scripts/push-staging.py
  scripts/update-maven-artifacts.py
  scripts/update-tests-maven-repo.py
  scripts/update-tests.py
Labels: needs review :mag:

#200 KOGITO-2767 Fix master to 1.0.0-snapshot version
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  modules/kogito-trusty/module.yaml
  scripts/update-maven-artifacts.py
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: needs review :mag:

#204 [KOGITO-2912][KOGITO-2855][KOGITO-2946] Cherry-picking scripts change for future 0.13.1 release
  Jenkinsfile-Nightly
  Jenkinsfile.deploy
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-springboot-s2i/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/manage-kogito-version.py
  scripts/push-staging.py
  scripts/update-maven-artifacts.py
  scripts/update-tests-maven-repo.py
  scripts/update-tests.py
Labels: needs review :mag:, on hold :hand:

#213 [0.13.x][KOGITO-3024][cherry-pick] S2i archetype: rm only process file
  modules/kogito-s2i-core/added/s2i-core
Labels: cherry-pick :cherries:, needs review :mag:

#210 [KOGITO-3024] S2i Archetype build: remove only process file
  modules/kogito-s2i-core/added/s2i-core
Labels: ready :rocket:

#208 [KOGITO-1934] - Add a flag on the push-staging.py script to allow-ove…
  Makefile
  README.md
  scripts/README.md
  scripts/push-staging.py
Labels: needs review :mag:

#211 [KOGITO-3010] - Add kie-github-ci-bot to kogito-images repository
  .github/bot-files/comments.yml
  .github/bot-files/labels.yml
  .github/bot-files/paths.yml
  .github/bot-files/reviewers.yml
Labels: ready :rocket:

#183 [KOGITO-2288][KOGITO-2289] Modify jenkinsfiles for release pipeline
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:, on hold :hand:

#215 [KOGITO-2888] Cleanup old pipeline(s)
  Jenkinsfile-Nightly
Labels: needs review :mag:

#218 KOGITO-2997 Set Maven native build in container
  Jenkinsfile
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#224 [KOGITO-2909] Promote pipeline: add release create
  Jenkinsfile.promote
Labels: needs review :mag:

#225 [KOGITO-3144] Zulip topic naming convention
  Jenkinsfile.promote
Labels: ready :rocket:

#226 small typo
  README.md
Labels: needs review :mag:
