Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-07, with the labels that each got.

#182 [KOGITO-2451][KOGITO-2478] Migrate nightly pipelines to RHBA
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  README.md
  modules/kogito-epel/7/configure
  scripts/manage-kogito-version.py
  scripts/update-maven-information.py
  scripts/update-tests-maven-repo.py
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:, on hold :hand:

#187 [KOGITO-2543] - Maven downloading process output not turned off for a…
  modules/kogito-s2i-core/added/s2i-core
Labels: ready :rocket:

#192 [KOGITO-2799] Harmonize Jenkinfiles
  Jenkinsfile
Labels: ready :rocket:

#189 [KOGITO-2046] - Remove "infinispan properties module" from Data Index…
  .github/workflows/run-bats-tests.yml
  README.md
  kogito-data-index-overrides.yaml
  kogito-jobs-service-overrides.yaml
  modules/kogito-data-index/added/kogito-app-launch.sh
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  modules/kogito-infinispan-properties/added/kogito-infinispan-properties.sh
  modules/kogito-infinispan-properties/configure
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-infinispan-properties/tests/bats/kogito-infinispan-properties.bats
  modules/kogito-jobs-service/added/kogito-app-launch.sh
  modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
  scripts/common.py
  tests/features/kogito-data-index.feature
  tests/features/kogito-jobs-service.feature
Labels: ready :rocket:

#194 [KOGITO-2867] Changes in scripts for next release
  README.md
  scripts/manage-kogito-version.py
  scripts/update-maven-information.py
Labels: ready :rocket:

#188 KOGITO 2707 - add trusty image
  .github/workflows/run-bats-tests.yml
  Jenkinsfile
  Jenkinsfile-Nightly
  Jenkinsfile.deploy
  Jenkinsfile.promote
  Makefile
  README.md
  kogito-imagestream.yaml
  kogito-trusty-overrides.yaml
  modules/kogito-trusty/added/kogito-app-launch.sh
  modules/kogito-trusty/added/launch/kogito-trusty.sh
  modules/kogito-trusty/configure
  modules/kogito-trusty/module.yaml
  modules/kogito-trusty/tests/bats/kogito-trusty.bats
  scripts/common.py
  scripts/push-local-registry.sh
  scripts/push-staging.py
  scripts/update-maven-information.py
  tests/features/common.feature
  tests/features/kogito-trusty.feature
Labels: needs review :mag:
