Repository apache/incubator-kie-kogito-images, pull requests merged in 2020-06, with the labels that each got.

#170 [KOGITO-2352] Allow to change repository on update artifacts script
  scripts/update-artifacts.py
Labels: needs review :mag:

#169 [KOGITO-2123] - Remove duplicate BATS test
  modules/kogito-data-index/tests/bats/kogito-data-index.bats
  modules/kogito-infinispan-properties/tests/bats/kogito-infinispan-properties.bats
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
Labels: needs review :mag:

#165 [KOGITO-1861] - Make possible to turn the Maven downloading process o…
  README.md
  modules/kogito-maven/3.6.x/added/configure-maven.sh
  modules/kogito-maven/3.6.x/module.yaml
  modules/kogito-maven/tests/bats/maven-settings.bats
Labels: ready :rocket:

#171 [KOGITO-2357] Build & test against custom repo param
  Jenkinsfile.deploy
  scripts/update-artifacts.py
Labels: needs review :mag:

#172 [KOGITO-2370] Update artifacts should update kogito version
  scripts/common.py
  scripts/update-artifacts.py
Labels: needs review :mag:

#177 [KOGITO-2221] - Project generation for SpringBoot doesn't work on OpenShift
  modules/kogito-quarkus-s2i/s2i/bin/assemble
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/kogito-springboot-s2i/s2i/bin/assemble
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#181 [KOGITO-2445] maven repo added to tests only
  Jenkinsfile.deploy
  scripts/update-maven-information.py
  tests/features/kogito-springboot-ubi8-s2i.feature
Labels: on hold :hand:

#185 [KOGITO-2005] - Release Kogito Images 0.11.0
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#184 [KOGITO-2005] - Release Kogito Images 0.11.0
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-infinispan-properties/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:, ready :rocket:

#186 [Kogito-2475] - Migrate kogito-images PR check to RHBA jenkins
  Jenkinsfile
Labels: ready :rocket:
