Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-12, with the labels that each got.

#919 [KOGITO-6333] Enforce Jackson RestEasy in auto-generated projects
  modules/kogito-s2i-core/added/s2i-core
Labels: ready :rocket:

#920 [1.11.x] [RHPAM-4053] - Kogito builder image: Source file generation should us…
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
Labels: needs review :mag:, needs-cherry-pick :cherries:

#934 [main] [RHPAM-4053] - Kogito builder image: Source file generation sh…
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
Labels: needs review :mag:, cherry-pick :cherries:

#935 [1.14.x] [RHPAM-4053] - Kogito builder image: Source file generation …
  image.yaml
  modules/kogito-data-index-ephemeral/module.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-data-index-postgresql/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-jit-runner/module.yaml
  modules/kogito-jobs-service-ephemeral/module.yaml
  modules/kogito-jobs-service-infinispan/module.yaml
  modules/kogito-jobs-service-mongodb/module.yaml
  modules/kogito-jobs-service-postgresql/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-infinispan/module.yaml
  modules/kogito-trusty-postgresql/module.yaml
  modules/kogito-trusty-redis/module.yaml
  modules/kogito-trusty-ui/module.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:, cherry-pick :cherries:

#946 [1.11.x] BAPL-1990 conscious language
  scripts/common.py
Labels: needs review :mag:, needs-cherry-pick :cherries:

#933 BAPL-1990 conscious language
  scripts/common.py
Labels: needs review :mag:

#955 BXMSPROD-1577 Improved result message for nightlies
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: ready :rocket:

#972 [1.15.x] BXMSPROD-1577 Improved result message for nightlies (#955)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:, cherry-pick :cherries:

#973 [1.11.x] BXMSPROD-1577 Improved result message for nightlies (#955)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: cherry-pick :cherries:
