Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-01, with the labels that each got.

#308 [KOGITO-4115] Fix protobuf files location
  modules/kogito-persistence/added/kogito-persistence.sh
  modules/kogito-persistence/tests/bats/kogito-persistence.bats
Labels: ready :rocket:

#291 KOGITO-4070 - Remove image_metadata from images
  README.md
  modules/kogito-quarkus-s2i/s2i/bin/assemble
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/kogito-springboot-s2i/s2i/bin/assemble
Labels: needs review :mag:, on hold :hand:

#310 [KOGITO-4115] correct bats
  modules/kogito-persistence/tests/bats/kogito-persistence.bats
Labels: ready :rocket:

#318 KOGITO-4191: Fix Docker Image scripts for Task/Management Console
  README.md
  modules/kogito-management-console/added/launch/kogito-management-console.sh
  modules/kogito-task-console/added/launch/kogito-task-console.sh
Labels: needs review :mag:

#311 [KOGITO-1031] Add flag to ignore self-signed SSL certificate
  Jenkinsfile.deploy
  scripts/update-maven-artifacts.py
Labels: ready :rocket:

#326 Delete paths.yml
  .github/bot-files/paths.yml
Labels: ready :rocket:

#333 [1.2.x] Set version 1.2.0-snapshot
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-quarkus-jvm/module.yaml
  modules/kogito-quarkus-s2i/module.yaml
  modules/kogito-quarkus/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-springboot-s2i/module.yaml
  modules/kogito-springboot/module.yaml
  modules/kogito-system-user/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-ui/module.yaml
  modules/kogito-trusty/module.yaml
  tests/features/kogito-quarkus-ubi8-s2i.feature
  tests/features/kogito-springboot-ubi8-s2i.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#334 [1.2.x] KOGITO-4175 - Kogito Image for the new JIT DMN service in Kogito Apps Cherry pick
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  kogito-imagestream.yaml
  kogito-jit-runner-overrides.yaml
  modules/kogito-jit-dmn/added/kogito-app-launch.sh
  modules/kogito-jit-dmn/configure
  modules/kogito-jit-dmn/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/update-maven-artifacts.py
  tests/features/kogito-jit-dmn.feature
Labels: cherry-pick :cherries:, ready :rocket:

#317 KOGITO-4175 - Kogito Image for the new JIT DMN service in Kogito Apps
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  kogito-imagestream.yaml
  kogito-jit-runner-overrides.yaml
  modules/kogito-jit-dmn/added/kogito-app-launch.sh
  modules/kogito-jit-dmn/configure
  modules/kogito-jit-dmn/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/update-maven-artifacts.py
  tests/features/kogito-jit-dmn.feature
Labels: needs review :mag:

#336 KOGITO-4306 - Fix update-maven-artifacts for jit runner
  modules/kogito-jit-runner/added/kogito-app-launch.sh
  modules/kogito-jit-runner/configure
  modules/kogito-jit-runner/module.yaml
  scripts/common.py
  scripts/update-maven-artifacts.py
  tests/features/kogito-jit-runner.feature
Labels: needs review :mag:

#337 [1.2.x] KOGITO-4306 - Fix update-maven-artifacts for jit runner cherry pick
  modules/kogito-jit-runner/added/kogito-app-launch.sh
  modules/kogito-jit-runner/configure
  modules/kogito-jit-runner/module.yaml
  scripts/common.py
  scripts/update-maven-artifacts.py
  tests/features/kogito-jit-runner.feature
Labels: cherry-pick :cherries:, needs review :mag:
