Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-09, with the labels that each got.

#696 [KOGITO-5779] - Images failing due to no more existing kogito-quarkus-archetype
  README.md
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  tests/features/kogito-builder.feature
Labels: needs review :mag:

#706 [KOGITO-5779] - Images failing due to no more existing (#696)
  README.md
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  tests/features/kogito-builder.feature
Labels: needs review :mag:

#686 KOGITO-5781 Push reduced tag in deploy pipeline
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#712 [1.11.x] KOGITO-5781 Push reduced tag in deploy (#686)
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:, cherry-pick :cherries:

#715 RHPAM-3895 Correct rhpam runtime native behave
  tests/features/rhpam-kogito-runtime-native.feature
Labels: needs review :mag:

#719 [KOGITO-5851] - Build and deploy Quarkus from source files cannot be …
  modules/kogito-s2i-core/added/s2i-core
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:, needs-cherry-pick :cherries:

#720 [KOGITO-5851] - Build and deploy Quarkus from source files cannot be …
  modules/kogito-s2i-core/added/s2i-core
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:, cherry-pick :cherries:

#678 KOGITO-5730 Restructure DSL folders
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#742 [1.11.x] KOGITO-5730 Restructure DSL folders (#678)
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#748 [1.11.x] RHPAM-3895 Correct rhpam runtime native behave (#715)
  tests/features/rhpam-kogito-runtime-native.feature
Labels: ready :rocket:

#739 [KOGITO-3638] - Investigate failing Scenario
  tests/features/kogito-builder-native.feature
Labels: ready :rocket:
