Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-07, with the labels that each got.

#568 Update versions for 7.11.1 [1.5.x]
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-imagestream.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
Labels: needs review :mag:

#565 [KOGITO-5472] - Debug enabled scenarios are failing in kogito builder…
  tests/features/kogito-common-builder-jvm.feature
Labels: needs review :mag:

#577 [KOGITO-5494] PR checks on each maintained branch
  .jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#575 KOGITO-5480 Reorganized seed jobs & trigger automatically
  .jenkins/dsl/Jenkinsfile.seed
Labels: ready :rocket:

#583 [1.9.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#575)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#582 [1.8.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#575)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#581 [1.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#575)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#587 Fix set examples ref in behave tests
  scripts/common.py
Labels: needs review :mag:

#597 KOGITO-5532 Corrected PR check author handling
  Jenkinsfile
Labels: needs review :mag:

#603 Corrected RHPAM feature test with springboot
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: ready :rocket:

#606 bump version to 1.5.1-SNAPSHOT
  image.yaml
  kogito-imagestream.yaml
  modules/kogito-builder/module.yaml
  modules/kogito-custom-truststore/module.yaml
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-jit-runner/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/module.yaml
  modules/kogito-launch-scripts/module.yaml
  modules/kogito-logging/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-persistence/module.yaml
  modules/kogito-runtime-jvm/module.yaml
  modules/kogito-runtime-native/module.yaml
  modules/kogito-s2i-core/module.yaml
  modules/kogito-system-user/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-common/module.yaml
  modules/kogito-trusty-infinispan/module.yaml
  modules/kogito-trusty-redis/module.yaml
  modules/kogito-trusty-ui/module.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
Labels: ready :rocket:

#613 [1.9.x] Fix set examples ref in behave tests (#587)
  scripts/common.py
Labels: needs review :mag:

#607 [KOGITO-5526] - Native Runtime img missing module
  modules/kogito-runtime-native/added/kogito-app-launch.sh
Labels: ready :rocket:

#602 [KOGITO-5326] Setup deploy/promote notifications on demand
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:

#614 Fix set examples ref in behave tests (#587)
  scripts/common.py
Labels: ready :rocket:

#516 BXMSPROD-1265: Conscious language initiative
  .jenkins/dsl/test.sh
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  scripts/common.py
  scripts/manage-kogito-version.py
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/rhpam-kogito-builder-jvm.feature
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:
