Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-05, with the labels that each got.

#458 [KOGITO-5088] - Upgrade GraalVM to 21.x on Kogito Images
  README.md
  kogito-builder-overrides.yaml
  kogito-runtime-native-overrides.yaml
  modules/kogito-graalvm-installer/21.x-java-11/configure
  modules/kogito-graalvm-installer/21.x-java-11/module.yaml
  modules/kogito-graalvm-scripts/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-builder-jvm.feature
Labels: ready :rocket:

#449 [KOGITO-5056] - rhpam-kogito-builder-rhel8 image is using a wrong label
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:

#450 [1.5.x][KOGITO-5056] - rhpam-kogito-builder-rhel8 image is using a wrong label
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: cherry-pick :cherries:, ready :rocket:

#451 [KOGITO-5056] - rhpam-kogito-builder-rhel8 image is using a wrong label
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: cherry-pick :cherries:, ready :rocket:

#464 [RHPAM-3664] - Kogito images label is still pointing to
  image.yaml
  kogito-builder-overrides.yaml
  kogito-data-index-infinispan-overrides.yaml
  kogito-data-index-mongodb-overrides.yaml
  kogito-explainability-overrides.yaml
  kogito-jit-runner-overrides.yaml
  kogito-jobs-service-overrides.yaml
  kogito-management-console-overrides.yaml
  kogito-runtime-jvm-overrides.yaml
  kogito-runtime-native-overrides.yaml
  kogito-task-console-overrides.yaml
  kogito-trusty-infinispan-overrides.yaml
  kogito-trusty-redis-overrides.yaml
  kogito-trusty-ui-overrides.yaml
  tests/features/data-index/kogito-data-index-infinispan.feature
  tests/features/data-index/kogito-data-index-mongodb.feature
  tests/features/kogito-builder.feature
  tests/features/kogito-explainability.feature
  tests/features/kogito-jit-runner.feature
  tests/features/kogito-jobs-service.feature
  tests/features/kogito-management-console.feature
  tests/features/kogito-runtime-jvm.feature
  tests/features/kogito-runtime-native.feature
  tests/features/kogito-task-console.feature
  tests/features/rhpam-kogito-builder-jvm.feature
  tests/features/rhpam-kogito-runtime-jvm.feature
  tests/features/trusty/kogito-trusty-infinispan.feature
  tests/features/trusty/kogito-trusty-redis.feature
  tests/features/trusty/kogito-trusty-ui.feature
Labels: cherry-pick :cherries:, ready :rocket:

#467 [RHPAM-3656] - Red Hat Maven GA repository not available in Kogito S2…
  Makefile
  README.md
  modules/kogito-maven/3.6.x/configure
  modules/kogito-maven/3.6.x/maven/settings.xml
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  scripts/build-product-image.sh
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:, needs-cherry-pick :cherries:

#469 [RHPAM-3656] - Red Hat Maven GA repository not available in Kogito S2i
  Makefile
  README.md
  modules/kogito-maven/3.6.x/configure
  modules/kogito-maven/3.6.x/maven/settings.xml
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  scripts/build-product-image.sh
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: cherry-pick :cherries:, ready :rocket:

#470 [RHPAM-3654] - Wrong archetype used to generate project from provided…
  Makefile
  README.md
  modules/kogito-builder/added/kogito-app-launch.sh
  modules/kogito-builder/s2i/bin/assemble
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs-cherry-pick :cherries:, ready :rocket:

#471 [RHPAM-3654] - Wrong archetype used to generate project from provided…
  Makefile
  README.md
  modules/kogito-builder/added/kogito-app-launch.sh
  modules/kogito-builder/s2i/bin/assemble
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: cherry-pick :cherries:, needs review :mag:

#474 [KOGITO-5138] - Using latest ubi8 image for all Kogito images
  image.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-jit-runner/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-infinispan/module.yaml
  modules/kogito-trusty-redis/module.yaml
  modules/kogito-trusty-ui/module.yaml
Labels: needs review :mag:

#472 [KOGITO-4721] - Create Image distribution for Job Service MongoDB
  README.md
  kogito-jobs-service-ephemeral-overrides.yaml
  kogito-jobs-service-infinispan-overrides.yaml
  kogito-jobs-service-mongodb-overrides.yaml
  modules/kogito-jobs-service-common/added/launch/kogito-jobs-service-common.sh
  modules/kogito-jobs-service-common/configure
  modules/kogito-jobs-service-common/module.yaml
  modules/kogito-jobs-service-common/tests/bats/kogito-jobs-service-common.bats
  modules/kogito-jobs-service-ephemeral/added/kogito-app-launch.sh
  modules/kogito-jobs-service-ephemeral/configure
  modules/kogito-jobs-service-ephemeral/module.yaml
  modules/kogito-jobs-service-infinispan/added/kogito-app-launch.sh
  modules/kogito-jobs-service-infinispan/configure
  modules/kogito-jobs-service-infinispan/module.yaml
  modules/kogito-jobs-service-mongodb/added/kogito-app-launch.sh
  modules/kogito-jobs-service-mongodb/configure
  modules/kogito-jobs-service-mongodb/module.yaml
  modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
  modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
  scripts/common.py
  scripts/run-bats.sh
  scripts/update-maven-artifacts.py
  scripts/update-tests.py
  tests/features/jobs-service/kogito-jobs-service-common.feature
  tests/features/jobs-service/kogito-jobs-service-ehpemeral.feature
  tests/features/jobs-service/kogito-jobs-service-infinispan.feature
  tests/features/jobs-service/kogito-jobs-service-mongodb.feature
Labels: needs review :mag:

#475 [1.7.x] [KOGITO-5138] - Using latest ubi8 image for all Kogito images
  image.yaml
  modules/kogito-data-index-infinispan/module.yaml
  modules/kogito-data-index-mongodb/module.yaml
  modules/kogito-explainability/module.yaml
  modules/kogito-jit-runner/module.yaml
  modules/kogito-jobs-service/module.yaml
  modules/kogito-management-console/module.yaml
  modules/kogito-task-console/module.yaml
  modules/kogito-trusty-infinispan/module.yaml
  modules/kogito-trusty-redis/module.yaml
  modules/kogito-trusty-ui/module.yaml
Labels: cherry-pick :cherries:, needs review :mag:

#477 KOGITO-5179 Update jobs-service references
  Jenkinsfile.deploy
  Jenkinsfile.promote
  README.md
  kogito-imagestream.yaml
  scripts/README.md
  tests/features/common-custom-truststore.feature
  tests/features/jobs-service/kogito-jobs-service-ephemeral.feature
Labels: needs review :mag:

#476 [KOGITO-5178] - Create Image distribution for Job Service Postgresql
  README.md
  kogito-imagestream.yaml
  kogito-jobs-service-postgresql-overrides.yaml
  modules/kogito-jobs-service-postgresql/added/kogito-app-launch.sh
  modules/kogito-jobs-service-postgresql/configure
  modules/kogito-jobs-service-postgresql/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/update-maven-artifacts.py
  tests/features/common-custom-truststore.feature
  tests/features/jobs-service/kogito-jobs-service-common.feature
  tests/features/jobs-service/kogito-jobs-service-postgresql.feature
Labels: needs review :mag:

#487 KOGITO-4487 Update to nightly branch for testing
  Jenkinsfile.deploy
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#486 KOGITO-5184 Allow to promote images which were tested ok
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.deploy
  Jenkinsfile.promote
Labels: needs review :mag:

#399 [KOGITO-4455] Adding Kogito Quarkus Workflows extension to generated …
  modules/kogito-maven/3.6.x/configure
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  scripts/common.py
  tests/features/kogito-builder.feature
Labels: ready :rocket:
