Repository apache/incubator-kie-kogito-images, pull requests merged in 2021-06, with the labels that each got.

#506 [1.5.x] Update test script to dynamically update behave tests
  image.yaml
  scripts/common.py
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: ready :rocket:

#507 Update test script to dynamically update behave tests
  scripts/common.py
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: ready :rocket:

#510 [RHPAM-3654] - Wrong archetype used to generate project from provided…
  modules/kogito-s2i-core/added/s2i-core
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs review :mag:

#514 Update `openshift-template-validator` branch name to `main`
  .github/workflows/kogito-images-pr-check.yml
Labels: needs review :mag:

#515 [1.5.x] Update `openshift-template-validator` branch name to `main`
  .github/workflows/kogito-images-pr-check.yml
Labels: needs review :mag:

#512 [1.5.x][RHPAM-3654] - Wrong archetype used to generate project from provided…
  modules/kogito-s2i-core/added/s2i-core
  tests/features/kogito-builder.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: cherry-pick :cherries:, needs review :mag:

#526 [1.5.x][RHPAM-3735] - Red Hat Maven techpreview repository id is wrong in Ko…
  modules/kogito-maven/3.6.x/configure
Labels: needs review :mag:

#525 [RHPAM-3735] - Red Hat Maven techpreview repository id is wrong in Ko…
  modules/kogito-maven/3.6.x/configure
Labels: ready :rocket:

#535 [KOGITO-5363] Updated Maven version to 3.8.1
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-maven/3.8.x/added/configure-maven.sh
  modules/kogito-maven/3.8.x/configure
  modules/kogito-maven/3.8.x/maven/settings.xml
  modules/kogito-maven/3.8.x/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-builder-jvm.feature
Labels: ready :rocket:

#529 [KOGITO-4535] - New data index image for Postgresql variation
  README.md
  kogito-data-index-postgresql-overrides.yaml
  kogito-imagestream.yaml
  modules/kogito-data-index-postgresql/added/kogito-app-launch.sh
  modules/kogito-data-index-postgresql/configure
  modules/kogito-data-index-postgresql/module.yaml
  scripts/README.md
  scripts/common.py
  scripts/push-staging.py
  scripts/update-maven-artifacts.py
  tests/features/common-custom-truststore.feature
  tests/features/common.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/data-index/kogito-data-index-postgresql.feature
  tests/features/jobs-service/kogito-jobs-service-postgresql.feature
Labels: ready :rocket:
