Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-03, with the labels that each got.

#1136 [1.11.x] [RHPAM-4195] Enable multi-arch for existing builder and runtime JVM images
  content_sets.yaml
  modules/kogito-graalvm-installer/20.x-java-1.8/configure
  modules/kogito-graalvm-installer/20.x-java-11/configure
  modules/kogito-graalvm-installer/21.x-java-11/configure
  modules/kogito-graalvm-scripts/configure
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
Labels: ready :rocket:, needs-cherry-pick :cherries:

#1148 [RHPAM-4195] Enable multi-arch for existing builder and runtime JVM images
  content_sets.yaml
  modules/kogito-graalvm-installer/20.x-java-1.8/configure
  modules/kogito-graalvm-installer/20.x-java-11/configure
  modules/kogito-graalvm-installer/21.x-java-11/configure
  modules/kogito-graalvm-scripts/configure
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
Labels: needs review :mag:, cherry-pick :cherries:

#1145 [1.13.x] Community: Update for productization
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-graalvm-installer/21.x-java-11/module.yaml
  modules/kogito-graalvm-scripts/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-builder.feature
Labels: needs review :mag:

#1147 [1.13.x] [RHPAM-3680] - Kogito image Runtime JVM does not consider much the en…
  kogito-builder-overrides.yaml
  modules/kogito-image-dependencies/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
Labels: needs review :mag:

#1158 Correct SKIP_TESTS handling
  .ci/jenkins/Jenkinsfile.deploy
Labels: needs review :mag:

#1160 [1.18.x] Correct SKIP_TESTS handling
  .ci/jenkins/Jenkinsfile.deploy
Labels: needs review :mag:

#1159 [1.13.x] Correct SKIP_TESTS handling
  .ci/jenkins/Jenkinsfile.deploy
Labels: needs review :mag:

#1155 [1.13.x] Remove native checks
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  Makefile
  tests/features/kogito-builder-native.feature
Labels: needs review :mag:

#1149 [1.13.x] [RHPAM-4195] Enable multi-arch for existing builder and runtime JVM images
  content_sets.yaml
  modules/kogito-graalvm-installer/20.x-java-1.8/configure
  modules/kogito-graalvm-installer/20.x-java-11/configure
  modules/kogito-graalvm-installer/21.x-java-11/configure
  modules/kogito-graalvm-scripts/configure
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
Labels: needs review :mag:, cherry-pick :cherries:

#1167 [1.13.x] Batch backports from 1.11.x
  modules/kogito-builder/s2i/bin/assemble
  modules/kogito-maven/3.8.x/configure
  modules/kogito-openjdk/semeru-11-open/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
  modules/kogito-openjdk/semeru-11-open/configure.sh
  modules/kogito-openjdk/semeru-11-open/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
  scripts/common.py
  scripts/update-tests.py
Labels: needs review :mag:

#1168 [KOGITO-6215] - Improve logs on kogito-builder image while trying to …
  .github/pull_request_template.md
  RELEASE_NOTES.md
  modules/kogito-s2i-core/added/s2i-core
Labels: ready :rocket:

#1071 [KOGITO-4717]Remove JQ module from kogito images
  README.md
  kogito-builder-overrides.yaml
  kogito-runtime-jvm-overrides.yaml
  kogito-runtime-native-overrides.yaml
  modules/kogito-jq/clean.sh
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/added/kogito-kubernetes-client.sh
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
Labels: ready :rocket:, needs-cherry-pick :cherries:

#1171 [Kogito-4717]Remove JQ module from kogito images (#1071)
  README.md
  kogito-builder-overrides.yaml
  kogito-runtime-jvm-overrides.yaml
  kogito-runtime-native-overrides.yaml
  modules/kogito-jq/clean.sh
  modules/kogito-jq/module.yaml
  modules/kogito-kubernetes-client/added/kogito-kubernetes-client.sh
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
Labels: needs review :mag:

#1172 Update RELEASE_NOTES.md
  RELEASE_NOTES.md
Labels: ready :rocket:

#1197 [main] [RHPAM-4056] Remove unsupported OpenJ9 images.
  content_sets.yaml
  modules/kogito-openjdk/semeru-11-open/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
  modules/kogito-openjdk/semeru-11-open/configure.sh
  modules/kogito-openjdk/semeru-11-open/module.yaml
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
Labels: needs review :mag:

#1196 [1.13.x] [RHPAM-4056] Remove unsupported OpenJ9 images.
  content_sets.yaml
  modules/kogito-openjdk/semeru-11-open/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
  modules/kogito-openjdk/semeru-11-open/configure.sh
  modules/kogito-openjdk/semeru-11-open/module.yaml
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
Labels: needs review :mag:

#1195 [1.11.x] [RHPAM-4056] Remove unsupported OpenJ9 images.
  content_sets.yaml
  modules/kogito-openjdk/semeru-11-open/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
  modules/kogito-openjdk/semeru-11-open/configure.sh
  modules/kogito-openjdk/semeru-11-open/module.yaml
  rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
  rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
Labels: needs review :mag:
