Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-08, with the labels that each got.

#1278 [KOGITO-7394] - [SW] Productize the data-index-ephemeral image
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  Makefile
  RELEASE_NOTES.md
  kogito-data-index-ephemeral-overrides.yaml
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  modules/kogito-data-index-common/configure
  modules/kogito-data-index-ephemeral/community/added/kogito-app-launch.sh
  modules/kogito-data-index-ephemeral/community/configure
  modules/kogito-data-index-ephemeral/community/module.yaml
  modules/kogito-data-index-ephemeral/prod/added/kogito-app-launch.sh
  modules/kogito-data-index-ephemeral/prod/configure
  modules/kogito-data-index-ephemeral/prod/module.yaml
  osbs-extra/logic-data-index-ephemeral-rhel8/gating.yaml
  rhpam-kogito-imagestream.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
  scripts/build-kogito-apps-components.sh
  scripts/build-product-image.sh
  scripts/common.py
  scripts/list-images.py
  scripts/manage-kogito-version.py
  scripts/push-staging.py
  scripts/update-tests.py
  tests/features/common-build-runtime.feature
  tests/features/common-custom-truststore.feature
  tests/features/common.feature
  tests/features/kogito-common-runtime-jvm.feature
  tests/features/openshift-serverless-logic/logic-data-index-ephemeral.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#1309 Fix Data Index Ephemeral tests (#1308)
  tests/features/common-dynamic-resources.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/supporting-services-common.feature
Labels: ready :rocket:, cherry-pick :cherries:

#1311 [RHPAM-4451] - improve logs for quarkus bootstrap app
  modules/kogito-s2i-core/added/s2i-core
  tests/features/kogito-builder.feature
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: ready :rocket:

#1310 [RHPAM-4451] - Kogito Builder: IBM BAMOE image can not use the RHBQ m…
  modules/kogito-s2i-core/added/s2i-core
  tests/features/bamoe-kogito-builder-jvm.feature
Labels: ready :rocket:

#1312 rename image to tech-preview
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  tests/features/common-custom-truststore.feature
  tests/features/common-dynamic-resources.feature
  tests/features/common.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/openshift-serverless-logic/logic-data-index-ephemeral.feature
  tests/features/supporting-services-common.feature
Labels: needs review :mag:

#1313 rename image to tech-preview (#1312)
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  tests/features/common-custom-truststore.feature
  tests/features/common-dynamic-resources.feature
  tests/features/common.feature
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/openshift-serverless-logic/logic-data-index-ephemeral.feature
  tests/features/supporting-services-common.feature
Labels: ready :rocket:

#1315 update dataindex artifact to the latest version
  modules/kogito-data-index-ephemeral/prod/module.yaml
Labels: ready :rocket:

#1314 update dataindex artifact to the latest version
  modules/kogito-data-index-ephemeral/prod/module.yaml
Labels: ready :rocket:

#1316 [RHPAM-4450] - Kogito Builder: Rename rhpam-prod-profile to bamoe-pro…
  bamoe-kogito-builder-rhel8-overrides.yaml
  modules/bamoe-kogito-profile/configure
  modules/bamoe-kogito-profile/module.yaml
  modules/kogito-maven/3.6.x/configure
  modules/kogito-maven/3.8.x/configure
  tests/features/bamoe-kogito-builder-jvm.feature
Labels: ready :rocket:

#1317 [KOGITO-7744] - Move ENABLE_RH_MAVEN_REPO from maven module to prod m…
  RELEASE_NOTES.md
  modules/kogito-maven/3.6.x/configure
  modules/kogito-maven/3.8.x/configure
  modules/rhpam-kogito-prod-profile/configure
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/rhpam-kogito-builder-jvm.feature
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#1321 [KOGITO-7700] - Allow adding quarkus extensions when building from
  RELEASE_NOTES.md
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/module.yaml
  tests/features/kogito-builder.feature
Labels: ready :rocket:

#1323 KOGITO-7785 Setup init-branch job
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/dsl/jobs.groovy
  scripts/build-kogito-apps-components.sh
Labels: needs review :mag:
