Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-12, with the labels that each got.

#1350 KOGITO-8062 DSL: Refactor environments and export to config
  .ci/jenkins/dsl/jobs.groovy
Labels: WIP :construction_worker_man:

#1389 set logic-data-index-ephemeral image version to 1.27.0
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  modules/kogito-data-index-ephemeral/prod/module.yaml
Labels: ready :rocket:, cherry-pick :cherries:

#1383 [main] Bump quarkus version to 2.15.0.Final
  image.yaml
  kogito-swf-builder-overrides.yaml
  tests/features/kogito-swf-builder.feature
Labels: backport-1.32.x
