Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-02, with the labels that each got.

#1068 [RHPAM-4143] - Exclude memory-limit.sh for non-native ocp image build
  modules/kogito-builder/s2i/bin/assemble
Labels: ready :rocket:, cherry-pick :cherries:

#1059 [1.11.x] [RHPAM-4143] Exclude memory-limit.sh for non-native image build
  modules/kogito-builder/s2i/bin/assemble
Labels: ready :rocket:, needs-cherry-pick :cherries:

#975 [KOGITO-6229] - Add Oracle DB Support to Data Index
  README.md
  kogito-data-index-oracle-overrides.yaml
  modules/kogito-data-index-oracle/added/kogito-app-launch.sh
  modules/kogito-data-index-oracle/configure
  modules/kogito-data-index-oracle/module.yaml
  scripts/update-maven-artifacts.py
  tests/features/data-index/kogito-data-index-oracle.feature
Labels: needs review :mag:

#1076 [1.17.x] [KOGITO-6229] - Add Oracle DB Support to Data Index (#975)
  README.md
  kogito-data-index-oracle-overrides.yaml
  modules/kogito-data-index-oracle/added/kogito-app-launch.sh
  modules/kogito-data-index-oracle/configure
  modules/kogito-data-index-oracle/module.yaml
  scripts/update-maven-artifacts.py
  tests/features/data-index/kogito-data-index-oracle.feature
Labels: ready :rocket:, cherry-pick :cherries:

#1126 [1.13.x] Prepare branch for productization
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/jobs.groovy
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:

#1132 [1.18.x] Update to GraalVM 21.3.1
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-graalvm-installer/21.x-java-11/module.yaml
  modules/kogito-graalvm-scripts/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
Labels: needs review :mag:

#1133 Update to GraalVM 21.3.1
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-graalvm-installer/21.x-java-11/module.yaml
  modules/kogito-graalvm-scripts/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
Labels: needs review :mag:
