Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-09, with the labels that each got.

#1325 [1.13.x] Enable the productized jobs
  .ci/jenkins/dsl/jobs.groovy
Labels: ready :rocket:

#1326 [1.13.x-blue] Enable the productized jobs
  .ci/jenkins/dsl/jobs.groovy
Labels: ready :rocket:

#1330 [KIECLOUD-655] - Prepare Kogito images for 7.13.1 and 8.0.1
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-imagestream.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
Labels: ready :rocket:

#1331 [1.13.x-blue] [KIECLOUD-655] - Prepare Kogito images for 7.13.1 and 8.0.1
  README.md
  bamoe-kogito-builder-rhel8-overrides.yaml
  bamoe-kogito-imagestream.yaml
  bamoe-kogito-runtime-jvm-rhel8-overrides.yaml
  bamoe-kogito-runtime-native-rhel8-overrides.yaml
  modules/bamoe-kogito-profile/module.yaml
Labels: ready :rocket:

#1333 [1.27.x] set logic-data-index-ephemeral image version to 1.25.0
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  modules/kogito-data-index-ephemeral/prod/module.yaml
Labels: ready :rocket:

#1337 [1.28.x] [KOGITO-7974] Correct SWF testing
  tests/features/kogito-s2i-builder.feature
Labels: needs review :mag:, cherry-pick :cherries:

#1338 [KOGITO-7974] Correct SWF testing
  tests/features/kogito-s2i-builder.feature
Labels: needs review :mag:

#1342 KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/Jenkinsfile.update-prod-version
Labels: needs review :mag:

#1344 [1.28.x] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.init-branch
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/Jenkinsfile.update-prod-version
Labels: needs review :mag:

#1345 [1.13.x] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/Jenkinsfile.update-prod-version
  .ci/jenkins/dsl/Jenkinsfile.seed
Labels: needs review :mag:

#1346 [1.13.x-blue] KOGITO-8043 Jenkins node master -> built-in
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/Jenkinsfile.update-prod-version
  .ci/jenkins/dsl/Jenkinsfile.seed
Labels: needs review :mag:
