Repository apache/incubator-kie-kogito-images, pull requests merged in 2022-07, with the labels that each got.

#1286 Update GHA DSL check to use composite action
  .github/workflows/jenkins-tests-PR.yml
Labels: ready :rocket:

#1289 Correct DSL local testing
  .ci/jenkins/dsl/test.sh
Labels: needs review :mag:

#1288 [1.24.x] Update GHA DSL check to use composite action (#1286)
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:

#1283 [1.13.x-blue] [KOGITO-7456] - Rebranding changes on the kogito-images repository
  bamoe-kogito-builder-rhel8-overrides.yaml
  bamoe-kogito-imagestream.yaml
  bamoe-kogito-runtime-jvm-rhel8-overrides.yaml
  bamoe-kogito-runtime-native-rhel8-overrides.yaml
  modules/kogito-builder/s2i/bin/usage
  modules/kogito-runtime-jvm/s2i/bin/usage
  modules/kogito-runtime-native/s2i/bin/usage
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/rhpam-kogito-prod-profile/module.yaml
  rhpam-kogito-imagestream.yaml
  scripts/common.py
  tests/features/bamoe-kogito-builder-jvm.feature
  tests/features/bamoe-kogito-runtime-jvm.feature
  tests/features/bamoe-kogito-runtime-native.feature
  tests/features/common-build-runtime.feature
  tests/features/common-custom-truststore.feature
  tests/features/common-dynamic-resources.feature
  tests/features/common.feature
  tests/features/kogito-common-builder-jvm.feature
  tests/features/kogito-common-runtime-jvm.feature
  tests/features/kogito-common-runtime-native.feature
Labels: needs review :mag:

#1290 Setup some test corrections for blue
  scripts/README.md
  scripts/common.py
  tests/features/bamoe-kogito-builder-jvm.feature
  tests/features/bamoe-kogito-runtime-jvm.feature
  tests/features/bamoe-kogito-runtime-native.feature
Labels: needs review :mag:

#1291 [KOGITO-7504] Update Maven to 3.8.6
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-maven/3.8.x/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-builder-jvm.feature
Labels: needs review :mag:

#1293 [KOGITO-7504] Update Maven to 3.8.6
  README.md
  kogito-builder-overrides.yaml
  modules/kogito-maven/3.8.x/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-builder-jvm.feature
Labels: ready :rocket:

#1295 revert back extra_dir value to rhpam as it is a local path in the repository
  bamoe-kogito-builder-rhel8-overrides.yaml
  bamoe-kogito-runtime-jvm-rhel8-overrides.yaml
  bamoe-kogito-runtime-native-rhel8-overrides.yaml
Labels: ready :rocket:

#1296 [1.13.x] Correct testing after change of component
  tests/features/bamoe-kogito-builder-jvm.feature
  tests/features/bamoe-kogito-runtime-jvm.feature
  tests/features/bamoe-kogito-runtime-native.feature
Labels: ready :rocket:

#1297 [1.13.x-blue] Reactivate community native image build
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: ready :rocket:

#1298 [1.13.x] Reactivate community native image build (#1297)
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: ready :rocket:

#1300 [1.13.x-blue][RHPAM-4452] - Kogito-runtime-native (techpreview): Image does not re…
  Makefile
  bamoe-kogito-runtime-native-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-runtime-native.feature
Labels: ready :rocket:

#1301 [1.13.x][RHPAM-4452] - Kogito-runtime-native (techpreview): Image does not re…
  Makefile
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
  tests/features/kogito-builder-native.feature
  tests/features/kogito-common-runtime-native.feature
Labels: needs review :mag:, needs-cherry-pick :cherries:

#1302 [RHPAM-4452] - Kogito-runtime-native (techpreview): Image does not re…
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
  tests/features/kogito-common-runtime-native.feature
Labels: needs review :mag:
