Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-02, with the labels that each got.

#1422 [1.33.x] Fix Clone repos
  scripts/common.py
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#1424 Correct update quarkus command
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#1421 Fix Clone repos
  scripts/common.py
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#1426 Correct promote pipeline
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-1.34.x

#1430 Remove CI env var
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#1431 set logic-data-index-ephemeral image version to 1.28.0
  logic-data-index-ephemeral-rhel8-overrides.yaml
  logic-imagestream.yaml
  modules/kogito-data-index-ephemeral/prod/module.yaml
Labels: needs review :mag:, backport-1.34.x

#1433 [1.13.x] [RHPAM-4560] download maven 3.8.1 from brew instead of upstream
  modules/kogito-maven/3.8.x/module.yaml
Labels: needs review :mag:, backport-1.13.x-blue

#1436 [1.13.x] Fix PR check
  .ci/jenkins/Jenkinsfile
Labels: needs review :mag:

#1434 [KOGITO-8671] Update native env handling
  README.md
  modules/kogito-s2i-core/added/s2i-core
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:

#1439 KOGITO-8672 Correct shell tests to have image version
  Makefile
  tests/shell/kogito-swf-builder/RunTests.java
  tests/shell/kogito-swf-builder/resources/Dockerfile
  tests/shell/run.sh
Labels: needs review :mag:, backport-1.34.x

#1440 [1.13.x-blue] Fix PR check
  .ci/jenkins/Jenkinsfile
Labels: needs review :mag:

#1443 KIECLOUD-688 Use rhel8 for podman jobs
  .ci/jenkins/Jenkinsfile.promote
Labels: needs review :mag:

#1446 [RHPAM-4560] - Install maven from rpm
  modules/kogito-maven/3.8.x-rpm/added/configure-maven.sh
  modules/kogito-maven/3.8.x-rpm/configure
  modules/kogito-maven/3.8.x-rpm/maven/settings.xml
  modules/kogito-maven/3.8.x-rpm/module.yaml
  modules/kogito-maven/maven-dnf-module/artifacts/maven.module
  modules/kogito-maven/maven-dnf-module/configure
  modules/kogito-maven/maven-dnf-module/module.yaml
  rhpam-kogito-builder-rhel8-overrides.yaml
Labels: ready :rocket:, needs-cherry-pick :cherries:

#1448 [1.13.x-blue][RHPAM-4560] - Install maven from rpm
  bamoe-kogito-builder-rhel8-overrides.yaml
  modules/kogito-maven/3.8.x-rpm/added/configure-maven.sh
  modules/kogito-maven/3.8.x-rpm/configure
  modules/kogito-maven/3.8.x-rpm/maven/settings.xml
  modules/kogito-maven/3.8.x-rpm/module.yaml
  modules/kogito-maven/maven-dnf-module/artifacts/maven.module
  modules/kogito-maven/maven-dnf-module/configure
  modules/kogito-maven/maven-dnf-module/module.yaml
Labels: ready :rocket:, cherry-pick :cherries:

#1415 KOGITO-8526: Data Index Adds quarkus profile 'kafka-events-support' by default
  RELEASE_NOTES.md
  modules/kogito-data-index-common/added/kogito-data-index-common.sh
  modules/kogito-data-index-common/configure
  modules/kogito-data-index-common/module.yaml
  modules/kogito-data-index-common/tests/bats/kogito-data-index-common.bats
  modules/kogito-data-index-ephemeral/community/added/kogito-app-launch.sh
  modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
  modules/kogito-data-index-mongodb/added/kogito-app-launch.sh
  modules/kogito-data-index-oracle/added/kogito-app-launch.sh
  modules/kogito-data-index-postgresql/added/kogito-app-launch.sh
  tests/features/data-index/kogito-data-index-common.feature
Labels: needs review :mag:, on hold :hand:

#1365 KOGITO-5784 Use nightly Quarkus platform in PR / nightlies
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
  .ci/jenkins/dsl/jobs.groovy
  Makefile
  README.md
  image.yaml
  kogito-swf-builder-overrides.yaml
  modules/kogito-maven/3.6.x/added/configure-maven.sh
  modules/kogito-maven/3.6.x/module.yaml
  modules/kogito-maven/3.8.x-rpm/added/configure-maven.sh
  modules/kogito-maven/3.8.x-rpm/module.yaml
  modules/kogito-maven/3.8.x/added/configure-maven.sh
  modules/kogito-maven/3.8.x/module.yaml
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  modules/kogito-swf-builder/added/add-extension.sh
  modules/kogito-swf-builder/added/build-app.sh
  modules/kogito-swf-builder/added/create-app.sh
  modules/kogito-swf-builder/added/run-app-devmode.sh
  scripts/README.md
  scripts/build-quarkus-app.sh
  scripts/common.py
  scripts/manage-kogito-version.py
  scripts/setup-maven.sh
  scripts/update-quarkus-version.py
  scripts/update-repository.py
  tests/features/kogito-s2i-builder.feature
  tests/shell/kogito-swf-builder/RunTests.java
  tests/shell/kogito-swf-builder/resources/Dockerfile
  tests/test-apps/clone-repo.sh
Labels: needs review :mag:, dsl-test

#1444 [KOGITO-8642] Add Smallrye Health Checks to SW Builder
  RELEASE_NOTES.md
  modules/kogito-maven/3.8.x/added/configure-maven.sh
  modules/kogito-swf-builder/added/add-extension.sh
  modules/kogito-swf-builder/added/build-app.sh
  modules/kogito-swf-builder/added/configure-jvm-mvn.sh
  modules/kogito-swf-builder/added/create-app.sh
  modules/kogito-swf-builder/added/run-app-devmode.sh
  scripts/build-quarkus-app.sh
  scripts/setup-maven.sh
  tests/features/kogito-swf-builder.feature
Labels: needs review :mag:

#1451 [KOGITO-8741] - Kogito Images: Remove Maven 3.6.x module
  RELEASE_NOTES.md
  modules/kogito-maven/3.6.x/added/configure-maven.sh
  modules/kogito-maven/3.6.x/configure
  modules/kogito-maven/3.6.x/maven/settings.xml
  modules/kogito-maven/3.6.x/module.yaml
  modules/kogito-maven/tests/bats/maven-settings.bats
Labels: ready :rocket:

#1452 Fix Nightly quarkus platform
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: needs review :mag:
