Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-07, with the labels that each got.

#1617 KOGITO-9512 - Unify logic-swf-* image description with labels and fix…
  logic-data-index-ephemeral-rhel8-image.yaml
  logic-imagestream.yaml
  logic-swf-builder-rhel8-image.yaml
  logic-swf-devmode-rhel8-image.yaml
  tests/features/openshift-serverless-logic/logic-data-index-ephemeral.feature
  tests/features/openshift-serverless-logic/logic-swf-builder.feature
  tests/features/openshift-serverless-logic/logic-swf-devmode.feature
Labels: backport-1.40.x, backport-1.40.x-prod

#1626 build-quarkus-app.sh: include brotli4j native-linux-aarch64 artifact
  scripts/logic/build-quarkus-app.sh
Labels: backport-1.40.x-prod

#1624 Fix io.k8s.display-name for logic-swf-builder
  tests/features/openshift-serverless-logic/logic-swf-builder.feature
Labels: backport-1.40.x-prod, backport-1.41.x

#1632 CI: Correct operator build with registry mirror
  .ci/jenkins/Jenkinsfile.build-image
Labels: backport-1.40.x, backport-1.40.x-prod, backport-1.41.x

#1636 [1.41.x] CI: Fix reduced tag push
  .ci/jenkins/Jenkinsfile.build-image
Labels: backport-1.40.x, backport-main, backport-1.40.x-prod

#1643 [KOGITO-9633] - tzdb.dat (No such file or directory)
  modules/kogito-openjdk/11-headless/module.yaml
  modules/kogito-openjdk/11/module.yaml
Labels: backport-1.13.x-blue-next, backport-1.13.x-next, backport-1.42.x

#1610 [KOGITO-9465] - Fix behave test for the kogito-s2i-builder image
  Makefile
  tests/features/kogito-common-builder-jvm.feature
  tests/features/kogito-s2i-builder-native.feature
Labels: backport-1.13.x-blue-next, backport-1.13.x-next, backport-1.42.x

#1642 KOGITO-9616 Improve release notes
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-1.42.x

#1641 [1.40.x-prod] Make shell tests more flexible
  Makefile
  scripts/logic/test/behave_test.sh
  scripts/logic/test/env_test.sh
  scripts/logic/test/shell_test.sh
  tests/shell/kogito-swf-builder/RunTests.java
  tests/shell/kogito-swf-builder/resources/Dockerfile
  tests/shell/kogito-swf-devmode/RunTests.java
  tests/shell/run.sh
Labels: backport-main

#1657 [1.40.x-prod] Prod test script: Allow to use community images
  scripts/logic/test/env_test.sh
Labels: backport-1.40.x
