Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-05, with the labels that each got.

#1502 [1.13.x] RHPAM-4680 maven rpm module should include Red Hat repositories
  modules/kogito-maven/3.8.x-rpm/configure
  modules/kogito-maven/3.8.x-rpm/maven/settings.xml
Labels: backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next

#1498 [1.13.x] Setup prod CI
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/dsl/jobs.groovy
  Makefile
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next

#1514 [main] Bump Quarkus version to 2.16.7.Final
  image.yaml
  tests/features/kogito-swf-builder.feature
Labels: backport-1.38.x

#1521 Setup prod CI for next branch
  .ci/jenkins/dsl/jobs.groovy
Labels: backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next

#1525 [1.13.x] Corrected DSL for next branch
  .ci/jenkins/dsl/jobs.groovy
Labels: backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next

#1517 KOGITO-9058 Remove full quarkus platform dependency
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  Makefile
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-swf/builder/added/create-app.sh
  scripts/build-quarkus-app.sh
Labels: backport-1.38.x

#1552 KOGITO-9259 CI: Update nodes to rhel8
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/Jenkinsfile.setup-branch
  .ci/jenkins/Jenkinsfile.update-prod-version
  .ci/jenkins/dsl/jobs.groovy
  Makefile
  tests/test-apps/clone-repo.sh
Labels: backport-1.13.x, backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next, backport-1.39.x

#1556 KOGITO-9259 CI: Update nodes to rhel8
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/jobs.groovy
  Makefile
  tests/test-apps/clone-repo.sh
Labels: backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next
