Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-01, with the labels that each got.

#1400 [KOGITO-8420/8421] - auto configure jvm and few tweaks
  Makefile
  README.md
  modules/kogito-base-builder/module.yaml
  modules/kogito-dynamic-resources/added/java-default-options
  modules/kogito-swf-builder/added/add-extension.sh
  modules/kogito-swf-builder/added/build-app.sh
  modules/kogito-swf-builder/added/create-app.sh
  modules/kogito-swf-builder/added/jvm-settings.sh
  modules/kogito-swf-builder/configure.sh
  modules/kogito-swf-builder/tests/bats/kogito-swf-builder-jvm-settings.bats
  scripts/build-quarkus-app.sh
  scripts/common.py
  scripts/list-images.py
  scripts/run-bats.sh
  tests/features/kogito-swf-builder.feature
  tests/shell/kogito-swf-builder/build-and-run.sh
  tests/shell/kogito-swf-builder/resources/Dockerfile
  tests/test-apps/clone-repo.sh
Labels: ready :rocket:

#1401 [KOGITO-8429] - [SWF-Builder] Copy only the supported files into the …
  RELEASE_NOTES.md
  modules/kogito-swf-builder/added/build-app.sh
  tests/shell/kogito-swf-builder/resources/.mvn/jvm.config
Labels: needs review :mag:

#1402 [KOGITO-8421] - [SW] Ensure that the Kogito SW builder image has the …
  modules/kogito-swf-builder/added/add-extension.sh
  modules/kogito-swf-builder/added/build-app.sh
  modules/kogito-swf-builder/added/create-app.sh
  modules/kogito-swf-builder/added/jvm-settings.sh
  modules/kogito-swf-builder/tests/bats/kogito-swf-builder-jvm-settings.bats
  scripts/build-quarkus-app.sh
  tests/features/kogito-swf-builder.feature
  tests/shell/kogito-swf-builder/build-and-run.sh
Labels: needs review :mag:

#1405 [KOGITO-8472] - CeKit Validator Unrecognized field entrypoint
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: needs review :mag:

#1406 [KOGITO-8509] - CeKit Validator Unrecognized field service
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: needs review :mag:

#1408 KOGITO-8510 Solve kogito-swf-builder long builds
  modules/kogito-swf-builder/added/add-extension.sh
  modules/kogito-swf-builder/added/build-app.sh
  modules/kogito-swf-builder/added/create-app.sh
  scripts/build-quarkus-app.sh
  tests/shell/kogito-swf-builder/build-and-run.sh
  tests/shell/kogito-swf-builder/resources/Dockerfile
Labels: needs review :mag:

#1407 Pipelines: Update Cekit path
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: ready :rocket:, backport-1.33.x, backport-1.13.x, backport-1.13.x-blue

#1410 KOGITO-8393 Clean release notes on branching
  .ci/jenkins/Jenkinsfile.setup-branch
  RELEASE_NOTES.md
Labels: needs review :mag:

#1412 [1.33.x] Pipelines: Update Cekit path (#1407)
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: ready :rocket:, cherry-pick :cherries:

#1414 [1.13.x-blue] Pipelines: Update Cekit path (#1407)
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
Labels: needs review :mag:, cherry-pick :cherries:

#1413 [1.13.x] Pipelines: Update Cekit path (#1407)
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.deploy
Labels: needs review :mag:, cherry-pick :cherries:

#1418 KOGITO-8532 - Remove usage of deprecated Infinispan properties
  README.md
  contrib/jobs-service/container-compose-infinispan.yaml
  kogito-data-index-infinispan-overrides.yaml
  kogito-trusty-infinispan-overrides.yaml
  tests/features/data-index/kogito-data-index-infinispan.feature
  tests/features/jobs-service/kogito-jobs-service-all-in-one.feature
  tests/features/jobs-service/kogito-jobs-service-infinispan.feature
  tests/features/trusty/kogito-trusty-infinispan.feature
Labels: needs review :mag:, backport-1.33.x
