Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-06, with the labels that each got.

#1560 KOGITO-9259 CI: Fix env variables missing
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-1.13.x, backport-1.13.x-blue, backport-1.13.x-blue-next, backport-1.13.x-next, backport-1.39.x

#1576 build-quarkus-app.sh: allow to copy local deployed artifacts when running as part of nightly
  scripts/logic/build-quarkus-app.sh
Labels: backport-1.40.x

#1575 [KOGITO-9315] Add Kogito Kubernetes extension to swf images
  modules/kogito-swf/builder/build-config/module.yaml
  modules/kogito-swf/devmode/build-config/module.yaml
  scripts/logic/build-quarkus-app.sh
Labels: backport-1.40.x

#1561 [KOGITO-9168] [KSW-Operator] Create the cekit image descriptor for SW…
  Makefile
  kogito-swf-devmode-image.yaml
  logic-imagestream.yaml
  logic-swf-devmode-rhel8-image.yaml
  modules/kogito-swf/devmode/runtime/common/added/run-app-devmode.sh
  modules/kogito-swf/devmode/runtime/common/configure.sh
  modules/kogito-swf/devmode/runtime/common/module.yaml
  modules/kogito-swf/devmode/runtime/community/configure.sh
  modules/kogito-swf/devmode/runtime/community/module.yaml
  modules/kogito-swf/devmode/runtime/osl/configure.sh
  modules/kogito-swf/devmode/runtime/osl/module.yaml
  osbs-extra/logic-swf-devmode-rhel8/gating.yaml
  scripts/common.py
  scripts/list-images.py
  tests/features/kogito-swf-common.feature
  tests/features/kogito-swf-devmode.feature
  tests/features/openshift-serverless-logic/logic-swf-devmode.feature
Labels: backport-1.40.x

#1526 [KOGITO-9077] Create the cekit image descriptor for SWF builder image
  kogito-swf-builder-image.yaml
  logic-imagestream.yaml
  logic-swf-builder-rhel8-image.yaml
  modules/kogito-swf/builder/runtime/community/configure.sh
  modules/kogito-swf/builder/runtime/community/module.yaml
  modules/kogito-swf/builder/runtime/osl/configure.sh
  modules/kogito-swf/builder/runtime/osl/module.yaml
  osbs-extra/logic-swf-builder-rhel8/gating.yaml
  scripts/common.py
  tests/features/kogito-swf-common.feature
  tests/features/openshift-serverless-logic/logic-swf-builder.feature
Labels: backport-1.40.x

#1585 better organize quarkus-extensions variables in build-quarkus-app.sh
  scripts/logic/build-quarkus-app.sh
Labels: backport-1.40.x

#1572 KOGITO-9351 CI: Deploy: Externalize build image job
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.build-image
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/dsl/jobs.groovy
  .github/workflows/kogito-images-pr-check.yml
  scripts/build-kogito-apps-components.sh
  tests/test-apps/clone-repo.sh
Labels: backport-1.40.x

#1589 set OpenShift Serverless Logic productized images to version 1.30.0
  logic-data-index-ephemeral-rhel8-image.yaml
  logic-imagestream.yaml
  logic-swf-builder-rhel8-image.yaml
  logic-swf-devmode-rhel8-image.yaml
  modules/kogito-data-index-ephemeral/prod/module.yaml
  modules/kogito-swf/builder/runtime/osl/module.yaml
  modules/kogito-swf/devmode/runtime/osl/module.yaml
Labels: backport-1.40.x

#1595 set swf-builder and swf-devmode brew branches to OSL 1.30
  logic-swf-builder-rhel8-image.yaml
  logic-swf-devmode-rhel8-image.yaml
Labels: backport-1.40.x

#1597 CI: deploy pipeline small fix
  .ci/jenkins/Jenkinsfile.build-image
  .ci/jenkins/Jenkinsfile.deploy
  scripts/common.py
Labels: backport-1.40.x

#1599 CI: Build Image job should use build branch jenkinsfile
  .ci/jenkins/dsl/jobs.groovy
Labels: dsl-test, backport-1.40.x

#1604 KOGITO-9469 Set back Kogito Base Builder Image
  kogito-base-builder-image.yaml
  tests/features/common.feature
Labels: backport-1.40.x

#1605 [KOGITO-9450] - Fix behave test for the kogito-data-index-oracle image
  tests/features/data-index/kogito-data-index-oracle.feature
Labels: backport-1.40.x

#1612 [1.40.x-prod] Fix build-image job with specific repository
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.build-image
  .ci/jenkins/Jenkinsfile.deploy
  .ci/jenkins/Jenkinsfile.promote
  .ci/jenkins/dsl/jobs.groovy
  scripts/build-kogito-apps-components.sh
Labels: backport-1.40.x, backport-main
