Repository apache/incubator-kie-kogito-images, pull requests merged in 2023-03, with the labels that each got.

#1453 KOGITO-8778: Set http connector as default for data-index-ephemeral image
  RELEASE_NOTES.md
  kogito-data-index-ephemeral-overrides.yaml
  tests/features/data-index/kogito-data-index-common.feature
  tests/features/data-index/kogito-data-index-ephemeral.feature
  tests/features/data-index/kogito-data-index-infinispan.feature
  tests/features/data-index/kogito-data-index-mongodb.feature
  tests/features/data-index/kogito-data-index-oracle.feature
  tests/features/data-index/kogito-data-index-postgresql.feature
Labels: needs review :mag:, backport-1.35.x

#1455 [BXMSPROD-1976] enable backporting from all branches
  .github/workflows/pr-backporting.yml
Labels: ready :rocket:

#1458 [1.35.x] Bump Quarkus version to 2.13.7.Final
  image.yaml
  kogito-swf-builder-overrides.yaml
  tests/features/kogito-swf-builder.feature
Labels: needs review :mag:

#1461 DSL: Fix Prod PR check trigger phrase
  .ci/jenkins/dsl/jobs.groovy
Labels: needs review :mag:

#1460 [SRVLOGIC-76] Data-index prod ephemeral image is missing the KOGITO_D…
  logic-data-index-ephemeral-rhel8-overrides.yaml
  modules/kogito-data-index-ephemeral/prod/added/kogito-app-launch.sh
  tests/features/openshift-serverless-logic/logic-data-index-ephemeral.feature
Labels: needs review :mag:, backport-1.35.x

#1456 [main] Bump Quarkus version to 2.16.4.Final
  image.yaml
  tests/features/kogito-swf-builder.feature
Labels: needs review :mag:

#1463 [KIECLOUD-661] - Create pipeline for rhpam-kogito images
  Makefile
  scripts/build-osbs.sh
Labels: needs review :mag:, backport-1.13.x

#1465 [KIECLOUD-661] - small fix
  Makefile
  scripts/build-osbs.sh
Labels: needs-cherry-pick :cherries:, backport-1.13.x, backport-1.13.x-blue

#1467 [KIECLOUD-661] - add --assume-yues flag to the osbs builder
  Makefile
Labels: backport-1.13.x

#1471 Fix Setup Branch
  .ci/jenkins/Jenkinsfile.setup-branch
  scripts/common.py
  scripts/manage-kogito-version.py
  scripts/push-staging.py
Labels: backport-1.36.x

#1470 [RHPAM-4560] - Adjust rhpam-kogito-builder-rhel8 image to enable lice…
  modules/kogito-s2i-builder/added/kogito-app-launch.sh
  modules/kogito-s2i-builder/s2i/bin/assemble
  modules/kogito-s2i-core/added/s2i-core
  modules/kogito-s2i-core/tests/bats/s2i-core.bats
  rhpam-kogito-builder-rhel8-overrides.yaml
  rhpam-kogito-imagestream.yaml
  rhpam-kogito-runtime-jvm-rhel8-overrides.yaml
  rhpam-kogito-runtime-native-rhel8-overrides.yaml
  scripts/common.py
  tests/features/rhpam-kogito-builder-jvm.feature
Labels: needs-cherry-pick :cherries:, backport-1.13.x
